# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  disable:
    - errcheck  # Many Close() calls without error checking
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for this codebase

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
